-- Databricks notebook source
-- MAGIC %md
-- MAGIC # 02_RAG_Embeddings_Schema
-- MAGIC
-- MAGIC This notebook defines the embeddings table for the RAG documentation corpus.
-- MAGIC
-- MAGIC Source table:
-- MAGIC - `lending_catalog.sap_ai.doc_rag_corpus`
-- MAGIC
-- MAGIC Target table:
-- MAGIC - `lending_catalog.sap_ai.doc_rag_embeddings`
-- MAGIC
-- MAGIC The embeddings table copies the text and metadata from `doc_rag_corpus` and
-- MAGIC adds an `embedding` column (array of doubles) that will later hold vector
-- MAGIC embeddings generated by an embedding model (Databricks AI functions or an
-- MAGIC external LLM API).
-- MAGIC

-- COMMAND ----------

-- Databricks notebook source
USE CATALOG lending_catalog;
USE SCHEMA sap_ai;

CREATE TABLE IF NOT EXISTS doc_rag_embeddings (
    doc_id       STRING,
    topic        STRING,
    subtopic     STRING,
    chunk_index  INT,
    text         STRING,
    source       STRING,
    embedding    ARRAY<DOUBLE>,
    last_updated TIMESTAMP
);


-- COMMAND ----------

USE CATALOG lending_catalog;
USE SCHEMA sap_ai;

INSERT OVERWRITE TABLE doc_rag_embeddings
SELECT
    doc_id,
    topic,
    subtopic,
    chunk_index,
    text,
    source,
    CAST(NULL AS ARRAY<DOUBLE>) AS embedding,
    current_timestamp()          AS last_updated
FROM doc_rag_corpus;


-- COMMAND ----------

SELECT topic, subtopic, COUNT(*) AS chunks
FROM doc_rag_embeddings
GROUP BY topic, subtopic
ORDER BY topic, subtopic;


-- COMMAND ----------

SELECT doc_id, chunk_index, text, embedding
FROM doc_rag_embeddings
ORDER BY doc_id, chunk_index
LIMIT 10;
